### ISSUE TITLE
Группировка команд 

### ISSUE THREAD

**Issue by KomarDL** [KmXK/OSaSP#1]
https://github.com/KmXK/OSaSP/blob/274d9b661fb038171fac2e4022658ff0741cabae/Lab1/complile.s#L6
https://github.com/KmXK/OSaSP/blob/274d9b661fb038171fac2e4022658ff0741cabae/Lab1/complile.s#L7
https://github.com/KmXK/OSaSP/blob/274d9b661fb038171fac2e4022658ff0741cabae/Lab1/complile.s#L8

Необходимо перенаправить вывод всех (указанных выше) комад в поток ошибок за одно перенаправление. Это можно сделать с помощью группировки команд.

**Comment by KmXK** [comment]
Исправил.
