### ISSUE TITLE
Группировка команд

### ISSUE THREAD

**Issue by KomarDL** [KmXK/OSaSP#2]
https://github.com/KmXK/OSaSP/blob/274d9b661fb038171fac2e4022658ff0741cabae/Lab1/get_files_with_extension.s#L6
https://github.com/KmXK/OSaSP/blob/274d9b661fb038171fac2e4022658ff0741cabae/Lab1/get_files_with_extension.s#L7
https://github.com/KmXK/OSaSP/blob/274d9b661fb038171fac2e4022658ff0741cabae/Lab1/get_files_with_extension.s#L8
https://github.com/KmXK/OSaSP/blob/274d9b661fb038171fac2e4022658ff0741cabae/Lab1/get_files_with_extension.s#L9

Необходимо перенаправить вывод всех (указанных выше) комад в поток ошибок за одно перенаправление. Это можно сделать с помощью группировки команд.

**Comment by KmXK** [comment]
Исправил.
